### ISSUE TITLE
Updating tags without cleaning may generate duplicate items in tag toctree

### ISSUE THREAD

**Issue by melissawm** [melissawm/sphinx-tags#17]
Running sphinx without clearing the tags folder first may cause files to be added multiple times to the tag page toctree.

**Comment by nebelgrau77** [comment]
Yes, it does happen e.g. when you edit your tags, because maybe you decided afterwards to have them start with a capital letter.

One idea that comes to mind is to have sphinx_tags clean the folder using `os.remove()`, before it generates the tag index. What do you think? Could also have a boolean flag if someone does not want that to happen (although not sure what reasons for that could be).

**Comment by melissawm** [comment]
That sounds like a simple and easy solution. Currently I'm including it in makefiles when building the docs.

Do you want to submit a PR for it? 😄

**Comment by nebelgrau77** [comment]
Sure, will try! :)

**Comment by melissawm** [comment]
Probably around [here](https://github.com/melissawm/sphinx-tags/blob/896bb9c9344069e8cb00aa54efc2b45a732a87d2/src/sphinx_tags/__init__.py#L224) which is where the tags folder is created (if it doesn't exist already)

**Comment by nebelgrau77** [comment]
Right, that seems to be a good place, I will try.

**Comment by melissawm** [comment]
Closed by #27
