### ISSUE TITLE
Tags with more than one word

### ISSUE THREAD

**Issue by kassbohm** [melissawm/sphinx-tags#39]
If I create a tag consisting of **two** words, for example the tag "super important", I observe the following:

- This list of all tags (**tagsindex.html**) shows "super important", which is correct. :-)
- The list of pages using the tag "super important" (_tags/super%20important.html) is showing what should be shown. :-)
- But all pages tagged with "super important" show the **two** words "super" and "important" separated by a **comma**. And this is not intended, I think. Also: The respective hyperlinks are dead links...

I supposed, the intention is to also allow tags consisting of more than one word...?  

I would like to use also tags consisting of more than just one word. @melissawm Could you please...? :-)

**Comment by melissawm** [comment]
Definitely, thanks for the report! Also - if you are using this in a project would you be so kind as to leave a note at https://github.com/melissawm/sphinx-tags/discussions/32 ? Thanks!

**Comment by kassbohm** [comment]
> Definitely, thanks for the report! Also - if you are using this in a project would you be so kind as to leave a note at #32 ? Thanks!

I did read your request before. And sure: I will leave a note, as soon as I have some nice project to show...

**Comment by JWCook** [comment]
It seems common on sites with blog-style tags to hyphenate multi-word tags, and not use any characters that would have to be escaped in a URL. That has the advantage of tag URLs always being the same as the tag label, for example `site.com/tags/super-important`.

To make sure we don't generate broken links, options for this extension would be:
1. Raise a ValueError for any non-url-compatible characters. A quick way to check this is:
  ```python
  from urllib.parse import quote
  quote(tag_label) != tag_label
  ```
2. Automatically replace spaces with hyphens for generated tag URLs
  * Raise a ValueError for other special characters?
3. Allow any characters, fix tag display, and link to urlencoded tag URL

**Comment by JWCook** [comment]
Oh wait, it looks like other special characters are already handled correctly. I'm currently using tags like `status:draft`, which correctly generates a tag URL of `site.com/tags/status%3Adraft.html`.

So the only problem right now is with whitespace. I don't think this is solvable in a Sphinx extension, though, since this happens at the rST/Markdown parsing level. I think any tokens separated by whitespace are considered separate arguments (see [docutils docs here](https://docutils.sourceforge.io/docs/howto/rst-directives.html)). What a Sphinx directive has to work with are the arguments that have already been parsed and passed to it by Sphinx. So for something like this:
```rst
.. tags:: super important
```
'super' and 'important' will be passed to sphinx-tags as separate arguments, via `SphinxDirective.arguments`. I just tested this, and it looks like the current version of sphinx-tags doesn't generate dead links. I get links to two separate (valid) pages for tags 'super' and 'important'.

So I think the best solution here is for users to hyphenate multi-word tags.

**Comment by melissawm** [comment]
@JWCook do you want commit rights to do this? I'm happy to give you powers so you can iterate on it and we'll cut a release when that's done. What do you think?

**Comment by JWCook** [comment]
Sure, I think this can be done by basically undoing what the parser does (separating tokens by whitespace), and only using our own delimiter (','). That's deviating from the rST spec a bit, but I won't call the spec police if you don't!

You can add me to the repo as a contributor if you want, but I'll still plan on submitting a PR to make it easier to review.

**Comment by melissawm** [comment]
Sounds great, I'll do that!
