### ISSUE TITLE
Use sphinx-design to format tags as pills/buttons

### ISSUE THREAD

**Issue by melissawm** [melissawm/sphinx-tags#9]
See https://sphinx-design.readthedocs.io/en/latest/badges_buttons.html

**Comment by nebelgrau77** [comment]
I really like the buttons! But some questions come to mind:

- does this feature require sphinx-design extension? I'm using the RTD theme and it seems to be working out of the box, but maybe it only does with those specific themes mentioned in the link above (RTD, Alabaster and some others)? 
- would the sphinx_tags extension ideally turn tags into these buttons (or badges), i.e. instead of adding ``Tags: tag1, tag2`` in a tag file, add `` Tags: :bdg:`tag1`, :bdg-info:`tag2` ``? if that is the case, we could choose one style, say, info, but then how could the user choose different styles? I guess we would either need to stick to just one (and it could be selectable in the conf.py), or as an alternative cycle through the seven colors (primary/secondary/info/success... etc.)

**Comment by JWCook** [comment]
I'd really like to see this feature too.

> but then how could the user choose different styles

It would probably make the most sense to put that info in config. For example, a mapping from tag names to roles:
```python
tag_roles= {
    'tag_1': 'bdg',
    'tag_2': 'bdg-info',
    ...
}
```

That would:
1. Make using badges an opt-in feature
2. Make it not necessarily specific to sphinx-design (to allow for use with other extensions or custom roles)

**Comment by JWCook** [comment]
An incremental improvement to that would be glob patterns:
```python
tag_roles = {
    'tag_2': 'bdg-info',
    'prefix:*': 'bdg-warning',
    '*': 'bdg',  # default to 'bdg' role for any tags that don't match one of those patterns  
}
```


Quick example of matching those patterns using [`fnmatch`](https://docs.python.org/3/library/fnmatch.html):
```python
from fnmatch import fnmatch
from typing import Optional

def get_tag_role(tag: str, tag_roles: dict[str, str]) -> Optional[str]:
    """Check for a matching user-defined role for a given tag.
    Defaults to ``None`` for no role (plain text).
    """
    for pattern, role in tag_roles.items():
        if fnmatch(tag, pattern):
            return role
    return None

get_tag_role('tag_2', tag_roles)
# 'bdg-info'

get_tag_role('prefix:tag_3', tag_roles)
# 'bdg-warning'

get_tag_role('tag_1', tag_roles)
# 'bdg'

get_tag_role('tag_1', {})
# None
```
